spring:
  profiles:
    active: ${SPRING_PROFILE}

server:
  servlet:
    context-path: /api
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/DeployDB
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8088
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DEPLOY_DB_HOST}:${DEPLOY_DB_PORT}/${DEPLOY_DB_NAME}
    username: ${DEPLOY_DB_USER}
    password: ${DEPLOY_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
